
version: 2

sources:
  - name: jaffle_shop
    schema: jaffle_shop
    quoting:
      database: false
      schema: false
      identifier: false
    loader: stitch
    tables:
      - name: customers
      - name: orders
      - name: employees


models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
                    

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"


    - name: customers
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"

    - name: Invoca_ID
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"

    - name: ImportCommonRaw_ID
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"

macros:
  - name: my_macro
  
